version: "3.9"
services:
  api:
    build:
      context: ./src
    working_dir: /go/src
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - mysql
    environment:
      - "REDIS_HOST=redis:6380"
      - "PORT=8081"
      - "CORS_URL=http://localhost:3000"
      - "SQL_URL=postgres://db:5433/dmeeting?user=dmeeting&password=dmeeting_password&sslmode=disable"
  redis:
    image: redis
    ports:
      - "6380:6379"
    command: redis-server
  db:
    image: mysql:latest
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - ./dmeeting-platform/initdb:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=dmeeting
      - POSTGRES_PASSWORD=dmeeting_password
      - POSTGRES_DB=dmeeting
      - TZ=Asia/Tokyo

volumes:
  db:
