version: "3.9"
services:
  api:
    build:
      context: ./src
    working_dir: /go/src
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - db
    environment:
      - "REDIS_HOST=redis:6380"
      - "PORT=8081"
      - "CORS_URL=http://localhost:3000"
      - "SQL_URL=n4u:n4u-password@tcp(db:5433)/n4u-auth?charset=utf8mb4"
  redis:
    image: redis
    ports:
      - "6380:6379"
    command: redis-server
  db:
    image: mysql:latest
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/initdb:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "MYSQL_ROOT_PASSWORD=dmeeting_password"
      - "MYSQL_USER=n4u"
      - "MYSQL_PASSWORD=n4u-password"
      - "MYSQL_DATABASE=n4u-auth"
      - "TZ=Asia/Tokyo"

volumes:
  db:
