version: "3.9"
services:
  api:
    build:
      context: ./golang/src
    working_dir: /go/src
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - db
    environment:
      - "REDIS_HOST=redis:6380"
      - "PORT=8081"
      - "CORS_URL=http://localhost:3000"
      - "SQL_URL=s2113591:tsukuba@tcp(db:3306)/s2113591?charset=utf8"
  redis:
    image: redis
    ports:
      - "6380:6379"
    command: redis-server
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_ROOT_PASSWORD=dmeeting_password"
      - "MYSQL_USER=s2113591"
      - "MYSQL_PASSWORD=tsukuba"
      - "MYSQL_DATABASE=s2113591"
      - "TZ=Asia/Tokyo"

  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./front/app:/var/www/html

    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Japan

volumes:
  db:
