version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./app:/var/www/html

    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Japan
#    depends_on:
#      - reverseproxy